apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: test
  annotations:
      argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  username: YWRtaW4=  # base64 for "admin"
  password: cGFzc3dvcmQ=  # base64 for "password"