apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-b-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rrmavani/argocd-local-repo.git
    path: manifests/cluster-b/base
    targetRevision: main  
  destination:
    server: https://k3d-cluster-b-serverlb:6443
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true