replicaCount: 2
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
# Add annotations to ensure it deploys after pre-requisites
extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: helm-dummy-configmap
      namespace: my-namespace
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    data:
      dummy: "true"